### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xlsrln** [Ravaelles/Atlantis#13]
As suggested in the other thread, here is a post about the performance.

I downloaded the program and ran it vs the game AI and after maybe 5-10 minutes of elapsed game time, it started to run extremely slowly. I don't know why it does, but it happened every game I tried.

It also produced a lot of output; single numbers and "RunTo" errors, which may or may not be related.

**Comment by haopan27** [comment]
I've encountered something similar.

I got rid of all the System.out. stuff but the game still runs slowly after the first few minutes. In other words, there were no single numbers or "RunTo" errors. I've got a 'clean' log in the eclipse console:

Game table mapping not found.
Game table mapping not found.
0 | 7208 | 0 | 1127704875
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Connected
Connection successful
Connection successful, starting match...
Waiting...
Game ready!!!
Analyzing map... Map data ready.

Disconnected

**Comment by Purinho** [comment]
runTo and system prints do not cause the big issues

2 methods cause a lot of issues:
1. Select.enemy() is called a lot, whenever a combat is going on. the method will create a list of all enemy units with each call (and there may be many calls per frame, and many units to put into the list, ...)
2. Select.nearestTo() and all of its internal sorting is called a lot, whenever a combat is going on

I guess buffering the data of one or both of those methods may increase performance a lot

**Comment by Ravaelles** [comment]
Latest Atlantis version is using caching to fix this issue. Now the only performance issues I know of are related to trying to find a place for a building and failing to do so. Even then it is quite good on my machine.
