### ISSUE TITLE
ENV naming

### ISSUE THREAD

**Issue by MasterAqu** [Ravaelles/Atlantis#17]
I've created ENV folder, copied ENV-EXAMPLE and changed sc + chaoslauncher location in file. After I renamed ENV-EXAMPLE just to ENV -  getting alerts about ENV. What name file should be ?

**Comment by Ravaelles** [comment]
What kind of alerts are you getting exactly? I suspect `ENV file doesn't exist` ?

The `ENV` file should be within the root of your bot, exactly where `ENV-EXAMPLE` resides.

If you aren't sure where Java wants to search for the ENV file, just `System.out.println(envFilePath());` just [before this line](https://github.com/Ravaelles/Atlantis/blob/30fb249b08f3f06bee042ae711b6380c5b5f909f/src/atlantis/config/env/Env.java#L22).

Alternatively you could tweak [it here](https://github.com/Ravaelles/Atlantis/blob/30fb249b08f3f06bee042ae711b6380c5b5f909f/src/atlantis/config/env/Env.java#L58), by using `./ENV` or `../ENV` or anything you may need.

**Comment by MasterAqu** [comment]
Yup. ENV file doesn't exist. 
> The ENV file should be within the root of your bot, exactly where ENV-EXAMPLE resides.

Now it works! Thanks! And natural are corrected, yay! 🍡
