### ISSUE TITLE
Allow to select units behind fog of war in Select

### ISSUE THREAD

**Issue by Ravaelles** [Ravaelles/Atlantis#6]
## **Discussion and suggestions are greatly welcomed in Enhancement threads!**

Atlantis was meant to be used with BWAPI3 where you can access units behing FoW (Fog of War). BWAPI4+ forbids this, which complicates things, but is also a great occasion to make **Select** super-cool and super-handy.

My idea is to introduce **FoggedUnit** class, which would extend the **AUnit** (AUnit is Atlantis wrapper over inaccessible BWMirror Unit class; inaccessible because it's in external .jar with private constructor).

The biggest change would be to replace _Select.enemy()_ with:
`Select.enemyVisible()` , `Select.enemyFogged()` and `Select.enemyIncludingFogged()`

It would be incredibly helpful e.g. in situation where you want to look for enemy tanks in radius of 11 tiles (Shock Cannon range). This way one could simply use:
`Select.enemyIncludingFogged().ofType(Siege_Tank).inRadius(11, unit)`

This would return all discovered enemy tanks as accessible variables (via FoggedUnit wrapper), including those units we don't see. They're not actually BWAPI units, but our artificial entity called **FoggedUnit** which has:
- type
- position

Both **AUnit** and **FoggedUnit** should have `isFogged()` method which would return _true_ for fogged unit and _false_ for "real" unit. It's important because trying to issue `unit.attack(FoggedUnit)` would result in attacking Position, not the Unit, which often causes this terrible behavior of unit starting attack all the time, but never actually attacking.

I would love to hear constructive criticism as this change will affect Atlantis deeply and if handled poorly could lead to bad code readability (which is the only thing I want to avoid).

**Comment by certicky** [comment]
I gotta say I like it. It's a good way to deal with the fact that BWAPI4 doesn't allow us to access fogged units any more.

Small suggestion: 
FoggedUnit might also need something like "framesSinceLastSeen", so that you know how reliable the "position" is. And if you wanted to be too fancy, you could also compute and return the ever-growing area (polygon) where that unit could potentially be at the moment. But that's not really necessary now.

**Comment by andertavares** [comment]
Also, we can paint fogged units in a similiar way that UAlbertaBot does, so that we can see where the bot is expecting to find fogged enemies.

And if we want to get extremely fancy, we can implement something like Weber's particle filter to predict movement of fogged units.

**Comment by Ravaelles** [comment]
Can be now done this way: https://github.com/Ravaelles/Atlantis/blob/1b23ee66ff601f67b20e550c62df6eacb2cfaf16/src/atlantis/enemy/EnemyInformation.java#L213
