### ISSUE TITLE
Minor: jnativehook-2.1.0.jar missing in buildpath

### ISSUE THREAD

**Issue by sklett-src** [Ravaelles/Atlantis#8]
jnativehook-2.1.0.jar is not present in buildpath and needs to be added manually.

**Comment by Ravaelles** [comment]
You can use this page:
https://www.facebook.com/AtlantisBWAPI/

**Comment by Ravaelles** [comment]
Accidentally closed the issue. Will fix it when I get back home from holiday.

**Comment by Ravaelles** [comment]
All dependencies are now in `lib/` folder.
