### ISSUE TITLE
Unidentifiable log output

### ISSUE THREAD

**Issue by sklett-src** [Ravaelles/Atlantis#9]
Sometimes the console outputs single digit numbers, which are hard to track down in code.

**Comment by Ravaelles** [comment]
I'm on vacation right now, but could you please give an example of the output? 
Thanks!

**Comment by sklett-src** [comment]
an example would be just: 1\n1\n1\n1\n

I already tracked down the System.out. which caused it. It isnt that hard to track down but descriptive system outs are always nice.

**Comment by xlsrln** [comment]
I just downloaded this to try it out and ran the bot vs standard AI.

After a while the bot got really slow and started outputting things like this over and over:

> 0
> 0
> 0
> Vulture Spider Mine #323 RunTo empty
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> Vulture #307 RunTo empty
> 0
> 0
> 0

This has happened basically every time I've ran it and it doesn't seem optimal!

**Comment by sklett-src** [comment]
I ran into similar problems. Maybe open a new thread/issue for performance stuff? because there's a lot to discuss/talk about. Because of the limited time (85 ms) every bot has to be careful how often it iterates over lists (bwapi.getAllUnits...) every frame, so looking whether the code needlessly does that should solve the problem. I don't think there is a perfect solution for that, it depends on context, but in theory you only need to iterate over the unit list once every frame (or less).

edit: Also, remove all System.outs... I/O is just terrible for performance, if there's no benefit to it, remove it.

**Comment by xlsrln** [comment]
Just to be explicit, one of the causes of this is the line 

` System.out.println(defineOptimalConstantBunkerRepairers());` 

in ARepairCommander, line 97, which is spammed whenever there is a bunker worth repairing

**Comment by Ravaelles** [comment]
After major refactor, most of these should be gone now.
